import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# 设置网页配置
st.set_page_config(page_title="牙膏市场数据分析", layout="wide")

st.title("🦷 纳米羟基磷灰石牙膏 - 亚马逊市场分析")
st.markdown("上传 CSV 文件以生成交互式分析报表")

# 侧边栏上传文件
st.sidebar.header("数据上传区")
uploaded_us_file = st.sidebar.file_uploader("上传 US.csv (产品明细)", type=["csv"])
uploaded_brand_file = st.sidebar.file_uploader("上传 Brands.csv (品牌汇总)", type=["csv"])

# 数据清洗辅助函数
def clean_currency(x):
    if isinstance(x, str):
        return float(x.replace('$', '').replace(',', '').replace(' ', ''))
    return x

# --- Tab 1: 产品分析 (基于 US.csv) ---
if uploaded_us_file is not None:
    try:
        # 读取数据
        df_us = pd.read_csv(uploaded_us_file)
        
        # 简单的数据清洗 (根据你提供的文件列名)
        # 确保关键数值列是数字类型
        numeric_cols = ['月销量', '月销售额($)', '价格($)', '评分', '评分数']
        for col in numeric_cols:
            if col in df_us.columns:
                df_us[col] = df_us[col].apply(clean_currency)

        st.header("1. 产品维度分析 (Product Analysis)")
        
        # 关键指标卡片
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("总销售额", f"${df_us['月销售额($)'].sum():,.0f}")
        col2.metric("总销量", f"{df_us['月销量'].sum():,.0f}")
        col3.metric("平均价格", f"${df_us['价格($)'].mean():.2f}")
        col4.metric("平均评分", f"{df_us['评分'].mean():.2f} ⭐")

        # 图表区
        c1, c2 = st.columns(2)
        
        with c1:
            st.subheader("价格分布直方图")
            fig_price = px.histogram(df_us, x="价格($)", nbins=20, title="产品价格分布区间", color_discrete_sequence=['#36b9cc'])
            st.plotly_chart(fig_price, use_container_width=True)

        with c2:
            st.subheader("销量 vs 评分")
            fig_scatter = px.scatter(df_us, x="评分", y="月销量", size="价格($)", 
                                     hover_data=['品牌', '商品标题'], color="评分",
                                     title="评分与销量的关系 (气泡大小=价格)")
            st.plotly_chart(fig_scatter, use_container_width=True)

        st.subheader("Top 10 畅销单品")
        st.dataframe(df_us[['商品标题', '品牌', '价格($)', '月销量', '月销售额($)', '评分']].sort_values(by='月销量', ascending=False).head(10))

    except Exception as e:
        st.error(f"解析 US.csv 文件时出错: {e}")
        st.info("请确保上传了正确的文件格式。")

else:
    st.info("👈 请在左侧侧边栏上传 '...US.csv' 文件以查看产品分析。")

st.divider()

# --- Tab 2: 品牌分析 (基于 Brands.csv) ---
if uploaded_brand_file is not None:
    try:
        df_brand = pd.read_csv(uploaded_brand_file)
        
        # 清洗数据
        cols_to_clean = ['月销量', '月销售额($)', '平均价格($)', '市场份额']
        for col in cols_to_clean:
            if col in df_brand.columns:
                df_brand[col] = df_brand[col].apply(clean_currency)

        st.header("2. 品牌维度分析 (Brand Analysis)")

        # 布局
        b1, b2 = st.columns([2, 1])

        with b1:
            st.subheader("各品牌市场份额 (按月销售额)")
            # 过滤掉销售额极小的品牌以优化饼图显示
            top_brands = df_brand.sort_values(by='月销售额($)', ascending=False).head(15)
            fig_pie = px.pie(top_brands, values='月销售额($)', names='品牌', title='Top 15 品牌销售额占比', hole=0.4)
            st.plotly_chart(fig_pie, use_container_width=True)

        with b2:
            st.subheader("品牌均价对比 (Top 10 销量品牌)")
            top_vol_brands = df_brand.sort_values(by='月销量', ascending=False).head(10)
            fig_bar = px.bar(top_vol_brands, x='品牌', y='平均价格($)', title='头部品牌平均单价', color='平均价格($)')
            st.plotly_chart(fig_bar, use_container_width=True)

        st.subheader("品牌详细数据表")
        st.dataframe(df_brand)

    except Exception as e:
        st.error(f"解析 Brands.csv 文件时出错: {e}")
else:
    st.info("👈 请在左侧侧边栏上传 '...Brands.csv' 文件以查看品牌分析。")

# 页脚
st.markdown("---")
st.caption("数据来源: 上传的 CSV 文件 | Generated by Streamlit")